### ISSUE TITLE
configuration problem

### ISSUE THREAD

**Issue by mirkoperillo** [SIMPATICOProject/CDV#9] opened 2018-06-11 12:48 UTC
I have this error message in the console log of the browser starting CDV dashboard using run.sh docker script

```
14:43:40.128 ERROR Error: Error: apiEndpoint unreachable!
Stack trace:
d@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:54337
h</t.prototype.init/<@http://localhost/vendor.88f3c93820e6a28494f6.bundle.js:1:906586
t.prototype.invoke@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:61913
onInvoke@http://localhost/vendor.88f3c93820e6a28494f6.bundle.js:1:78540
t.prototype.invoke@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:61840
n.prototype.run@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:56800
p/<@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:54112
t.prototype.invokeTask@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:62598
onInvokeTask@http://localhost/vendor.88f3c93820e6a28494f6.bundle.js:1:78440
t.prototype.invokeTask@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:62511
n.prototype.runTask@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:57485
u@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:52644
t/this.invoke@http://localhost/polyfills.16577befed97e3fe93ee.bundle.js:1:63608
 vendor.88f3c93820e6a28494f6.bundle.js:1:4378
```
Which configuration is relative to this apiEndpoint ? Is it the cdvServer ?

```
 {
  "system": {
    "host":"http://cdv-server",
    "cdvServer":"http://cdv-server:8080"
    "aacServer":"http://aac:9500/aac",
    "account":"/account-manager/api/v1/accounts/",
    "pData":"/pdata-manager/api/v1/pData/",
    "downloadPData":"/pdata-manager/api/v1/pData/download",
    "pDataFields":"/service-manager/api/v1/pdatafields",
	"services":"/service-manager/api/v1/services",
    "clientId":"80e7a735-04bf-4737-b6ca-46caac64f823",
    "authority":"google",
   
    "cdvDashboardUrl":"/cdv-dashboard/simp_login/login2.html",
    "disable_auth":"true"
  },
  "i18n":{
  	"locale": "it"
  }
}
```

**Comment by enzosav** [comment] 2018-06-11 21:57
apiEndpoint refers on cdv-server. Check cdv-server docker container is reachable

**Comment by breningham** [comment] 2018-07-04 14:53
I am also having this issue, i have modified the config.json to the below contents: 
```(javascript)
 {
  "system": {
    "host":"http://cdv-dash.sparta.simpatico-project.eu",
    "cdvServer":"http://cdv.sparta.simpatico-project.eu"
    "aacServer":"http://auth.sparta.simpatico-project.eu/aac",
    "account":"/account-manager/api/v1/accounts/",
    "pData":"/pdata-manager/api/v1/pData/",
    "downloadPData":"/pdata-manager/api/v1/pData/download",
    "pDataFields":"/service-manager/api/v1/pdatafields",
	"services":"/service-manager/api/v1/services",
    "clientId":"d3298477-876d-4d6e-af67-5563698f557c",
    "authority":"google",
    "cdvDashboardUrl":"/cdv-dashboard/simp_login/login2.html",
    "disable_auth":"false"
  },
  "i18n":{
  	"locale": "en"
  }
}
```

I don't see a connection going out from chrome, however ALL resources it manages to load are actually redirects (304). maybe part of the problem? 
![screen shot 2018-07-04 at 15 52 27](https://user-images.githubusercontent.com/23170786/42283736-4a3a1cda-7fa2-11e8-9e96-fef249e07a3f.png)

**Comment by enzosav** [comment] 2018-07-05 08:33
The problem is a missing comma, after "cdvserver"..., just fixed in a previous commit in date 29th of May, please check and update code

**Closed as completed** 2018-10-01 08:47 UTC
